# Generated by Django 6.1.1 on 2026-09-14 08:45

import accounts.models
import accounts.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=accounts.models.EncryptedCharField(blank=True, max_length=255, null=True, validators=[accounts.validators.normalize_and_validate_phone]),
        ),
    ]
