# Generated by Django 6.1.1 on 2026-09-14 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_phone_number'),
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityslot',
            name='version',
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='held_by',
            field=models.ForeignKey(blank=True, db_column='held_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_reference_number',
            field=models.CharField(blank=True, db_index=True, help_text='UPI Reference Number / Bank UTR / Gateway Payment ID', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('hold', 'Hold'), ('locked', 'Locked'), ('booked', 'Booked')], default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['status', 'hold_expires_at'], name='availabilit_status_05b4a8_idx'),
        ),
    ]
