# Generated by Django 6.1.1 on 2026-09-14 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_remove_availabilityslot_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
